##
# Chatterbox

- name:  'Chatterbox Chat - start'
  uriPattern: 'chatterbox/chat/start'
  defaults:
    '@package': 'Sitegeist.Chatterbox'
    '@controller': 'OpenApiChat'
    '@action': 'start'
  httpMethods: ['POST']

- name:  'Chatterbox Chat - thread'
  uriPattern: 'chatterbox/chat/history'
  defaults:
    '@package': 'Sitegeist.Chatterbox'
    '@controller': 'OpenApiChat'
    '@action': 'history'
  httpMethods: ['GET']

- name: 'Chatterbox Chat - post'
  uriPattern: 'chatterbox/chat/post'
  defaults:
    '@package': 'Sitegeist.Chatterbox'
    '@controller': 'OpenApiChat'
    '@action': 'post'
  httpMethods: ['POST']
