Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.Chatterbox':
          position: 'before Neos.Neos'

  Neos:
    modules:
      management:
        submodules:
          chatterbox:
            label: 'Chatterbox Assistants'
            description: 'Manage Assitants'
            icon: 'icon-robot'
            controller: 'Sitegeist\Chatterbox\Controller\AssistantModuleController'
            privilegeTarget: 'Sitegeist.Chatterbox:ManageAssistants'
