Sitegeist:
  SchemeOnYou:
    documents:
      chatterbox:
        name: "Chatterbox IBE Endpoints"
        classNames:
          - 'Sitegeist\Chatterbox\Controller\OpenApiChatController'
  Chatterbox:
    enableLogging: false
    context: '%env:FLOW_CONTEXT%'

    #tools: [ ]
    #knowledge: []
    #instructions: []

Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.Chatterbox':
          position: 'before Neos.Neos'

  Neos:
    modules:
      management:
        submodules:
          chatterbox:
            label: 'Chatterbox AI-Assistants'
            description: 'Configure and test AI-Assitants'
            icon: 'icon-robot'
            controller: 'Sitegeist\Chatterbox\Controller\AssistantModuleController'
            privilegeTarget: 'Sitegeist.Chatterbox:ManageAssistants'
  Fusion:
    defaultContext:
      Chatterbox.Instruction: Sitegeist\Chatterbox\Helper\InstructionHelper
