Sitegeist:
  Chatterbox:
    organizations: []
    # orgId:
    #   discriminator: 'my-descriminator'
    #   accountId: 'abc'
    #   label: 'Neos Community'
    #    tools: []
    #    knowledge: []
    #    instructions: []
    #    messageEditors: []

Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.Chatterbox':
          position: 'before Neos.Neos'

  Neos:
    modules:
      management:
        submodules:
          chatterbox:
            label: 'Chatterbox AI-Assistants'
            description: 'Configure and test AI-Assitants'
            icon: 'icon-robot'
            controller: 'Sitegeist\Chatterbox\Controller\AssistantModuleController'
            privilegeTarget: 'Sitegeist.Chatterbox:ManageAssistants'
